# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[2,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The mod license
license="MIT"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="rpupdater" #mandatory
# The version number of the mod - there's a few well known null variables useable here or just hardcode it
version="1.0.0" #mandatory
# A display name for the mod
displayName="Resource Pack Updater" #mandatory
# A text field displayed in the mod UI
authors="Raconteur, SansMe69" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''Offer a set of actions for Fancy Menu buttons and ticker to update a resource pack.'''

[[dependencies.rpupdater]]
modId="neoforge"
type="required"
versionRange="[21.1.47,)"
ordering="NONE"
side="BOTH"

[[dependencies.rpupdater]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"